services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Thang123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pThang123"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    container_name: user_service
    restart: always
    env_file:
      - ./user-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  student-service:
    build: ./student-service
    container_name: student_service
    restart: always
    env_file:
      - ./student-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4002:4002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  payment-service:
    build: ./payment-service
    container_name: payment_service
    restart: always
    env_file:
      - ./payment-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4003:4003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  otp-service:
    build: ./otp-service
    container_name: otp_service
    restart: always
    env_file:
      - ./otp-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4004:4004"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  notification-service:
    build: ./notification-service
    container_name: notification_service
    restart: always
    env_file:
      - ./notification-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4005:4005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    restart: always
    env_file:
      - ./api-gateway/.env
    depends_on:
      user-service:
        condition: service_healthy
      student-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      otp-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    ports:
      - "4006:4006"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4006/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  mysql_data: