services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Thang123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pThang123"]
      interval: 30s
      timeout: 10s
      retries: 5

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    env_file:
      - ./user-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4001:4001"
    volumes:
      - ./user-service/src:/app/src
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile
    container_name: student_service
    restart: always
    env_file:
      - ./student-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4002:4002"
    volumes:
      - ./student-service/src:/app/src
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment_service
    restart: always
    env_file:
      - ./payment-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4003:4003"
    volumes:
      - ./payment-service/src:/app/src
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  otp-service:
    build:
      context: ./otp-service
      dockerfile: Dockerfile
    container_name: otp_service
    restart: always
    env_file:
      - ./otp-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4004:4004"
    volumes:
      - ./otp-service/src:/app/src
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification_service
    restart: always
    env_file:
      - ./notification-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4005:4005"
    volumes:
      - ./notification-service/src:/app/src
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: always
    env_file:
      - ./api-gateway/.env
    depends_on:
      user-service:
        condition: service_healthy
      student-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      otp-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    ports:
      - "4006:4006"
    volumes:
      - ./api-gateway/src:/app/src
      - /app/node_modules
    command: npm run dev

volumes:
  mysql_data:
